name: jpt1
channels:
  - conda-forge
  - defaults
  - nvidia  # Add if necessary for NVIDIA-specific packages
dependencies:
  - python=3.12.8  # Specify your desired Python version
  - scikit-learn=1.6.1
  - tokenizers
  - transformers
  - pip  # Ensure pip is available for installing pip-only packages
  - pip:
    # PyTorch nightly builds
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    # Other pip packages (will be installed from PyPI)
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - astroid==3.3.8
    - attrs==24.3.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.0
    - click==8.1.8
    - colorama==0.4.6
    - datasets==3.2.0
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gitdb==4.0.12
    - GitPython==3.1.44
    - huggingface-hub==0.27.0
    - idna==3.10
    - isort==5.13.2
    - Jinja2==3.1.4
    - joblib==1.4.2
    - MarkupSafe==3.0.2
    - mccabe==0.7.0
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - mypy-extensions==1.0.0
    - networkx==3.4.2
    - numpy==2.2.0
    - packaging==24.2
    - pandas==2.2.3
    - pathspec==0.12.1
    - pillow==11.0.0
    - platformdirs==4.3.6
    - propcache==0.2.1
    - protobuf==5.29.2
    - psutil==6.1.1
    - pyarrow==18.1.0
    - pydantic==2.10.4
    - pydantic_core==2.27.2
    - pylint==3.3.3
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - PyYAML==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.2
    - scipy==1.15.1
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - setuptools==75.6.0
    - six==1.17.0
    - smmap==5.0.2
    - sympy==1.13.1
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - tomlkit==0.13.2
    - tqdm==4.67.1
    - triton==3.2.0
    - typing_extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - wandb==0.19.1
    - xxhash==3.5.0
    - yarl==1.18.3
    - python-dotenv==1.1.0